AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >

  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    Environment:
      Variables:
        TABLE_NAME: greenhills-contacts
        AUTHORIZATION_TABLE_NAME: greenhills-authorization
  Api:
    Cors:
      AllowMethods: "'POST, PUT, GET, OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'//localhost:3000, //www.greenhillsconsultancy.co.uk'"

Resources:
  ContactDetailsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: MyLambdaRequestAuthorizer
        Authorizers:
          MyLambdaRequestAuthorizer:
            FunctionPayloadType: REQUEST
            FunctionArn: !GetAtt ContactDetailsAuthFunction.Arn
            # FunctionInvokeRole: !Ref MyRole
            Identity:
              Headers:
                - Origin
              # QueryStrings:
              #  - auth
              # NOTE: Additional options:
              # StageVariables:
              #   - AUTHORIZATION
              # Context:
              #   - authorization
              # ReauthorizeEvery: 100 # seconds

  ContactDetailsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: contactdetail
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      AutoPublishAlias: live
      DeploymentPreference:
        Type: Linear10PercentEvery1Minute
        Alarms:
          - Ref: AliasErrorMetricGreaterThanZeroAlarm
          - Ref: LatestVersionErrorMetricGreaterThanZeroAlarm
        Hooks:
          PreTraffic: !Ref GreenhillsNodejsServerPreTrafficHook
      MemorySize: 512
      Policies:
        - DynamoDBCrudPolicy:
            TableName: greenhills-contacts
      Events:
        ContactDetails:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref ContactDetailsApi
            Path: /details/{contact_id}
            Method: get
            # NOTE: Uncomment the two lines below to make `GET` publicly accessible
            # Auth:
            #   Authorizer: NONE

  ContactDetailsAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: requestauthorisation
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: greenhills-authorization

  AliasErrorMetricGreaterThanZeroAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: Lambda Function Error > 0
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Resource
          Value: !Sub "${ContactDetailsFunction}:live"
        - Name: FunctionName
          Value: !Ref ContactDetailsFunction
      EvaluationPeriods: 2
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 0

  LatestVersionErrorMetricGreaterThanZeroAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: Lambda Function Error > 0
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Resource
          Value: !Sub "${ContactDetailsFunction}:live"
        - Name: FunctionName
          Value: !Ref ContactDetailsFunction
        - Name: ExecutedVersion
          Value: !GetAtt ContactDetailsFunction.Version.Version
      EvaluationPeriods: 2
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 0

  GreenhillsNodejsServerPreTrafficHook:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: codedeployhook
      Handler: greenhills_nodejs_server_preTrafficHook.handler
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
                - "codedeploy:PutLifecycleEventHookExecutionStatus"
              Resource:
                !Sub 'arn:aws:codedeploy:${AWS::Region}:${AWS::AccountId}:deploymentgroup:${ServerlessDeploymentApplication}/*'
        - Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
                - "lambda:InvokeFunction"
              Resource: !Ref ContactDetailsFunction.Version
      Runtime: nodejs12.x
      FunctionName: 'CodeDeployHook_greenhills_nodejs_server_preTrafficHook'
      DeploymentPreference:
        Enabled: false
      Timeout: 30
      Environment:
        Variables:
          NewVersion: !Ref ContactDetailsFunction.Version

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ContactDetailsApiURL:
    Description: "API Gateway endpoint URL for Prod stage "
    Value: !Sub "https://${ContactDetailsApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  ContactDetailsFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt ContactDetailsFunction.Arn
  ContactDetailsFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt ContactDetailsFunctionRole.Arn
